export const rutasBO = {
    home: "/bo",
    mis_solicitudes: "mis-solicitudes",
    generar_boletin: "generar-boletin",
    normas: "normas",
    alta_solicitud: "alta-solicitud",
    detalle_solicitud: ":idNorma",
    editar_solicitud: "editar",
    observacion: "observacion",
    cotizar: "cotizar",
    diseniador_bo: "diseniador",
    vista_previa_bo: "vista-previa",
    firmar_bo: "firmar",
    ver_documentos_bo: "ver-documentos",
    detalle_boletin: "detalle-boletin",
    admin_sumario: "sumario",
    alta_seccion: "alta-seccion",
    secciones: "secciones",
    tipos_normas: "tipos-de-normas",
    subtipos_normas: "subtipos-de-normas",
    reparticiones: "reparticiones",
    feriados: "feriados",
    admin_usuarios: "administracion-usuarios",
    jerarquia: "jerarquia",
    boletines_publicados: "boletines-publicados",
    organismo_emisor: "organismo-emisor"
}
export const rutasSDIN = {
    home: "/sdin",
    importar_normas_bo: "importar-normas-bo",
    busqueda_avanzada: "busqueda-avanzada",
    mis_normas: "mis-normas",
    reportes: "reportes",
    nueva_norma: "nueva-norma",
    ficha_norma: "ficha-norma/:idNormaSDIN",
    ficha_norma_imagen: "ficha-norma/:idNormaSDIN/imagen/:numero",
    temas_front: "temas-front",
    temas: "temas",
    clases: "clases",
    relaciones_tipos: "relaciones-tipos",
    vista_previa_anexos: "vista-previa-anexos",
    administrador_digesto: "administrador-digesto",
    anexos: "anexos/:fecha",
    descriptores: "descriptores",
    temas_jerarquia: "jerarquia",
    causales: "causales",
    ramas: "ramas",
    patologias: "patologias",
    indice_tematico: "indice-tematico",
    tipos_de_norma: "tipos-de-norma",
    dependencias: "dependencias",
    logs: "logs"
}
export const rutasDJ = {
    home: "/dj",
    nueva_ley: "/dj/nueva-ley",
    abrogacion: "analisis-epistemologico/abrogacion/:idNormaSDIN",
    conflictos_normativos: "analisis-epistemologico/conflictos-normativos/:idNormaSDIN",
    perdida_vigencia_juridica: "analisis-epistemologico/perdida-vigencia-juridica/:idNormaSDIN",
    necesidad_refundir: "analisis-epistemologico/necesidad-refundir/:idNormaSDIN",
    necesidad_abrogacion: "analisis-epistemologico/necesidad-abrogacion/:idNormaSDIN",
    antecedentes_equivalencias: "analisis-epistemologico/antecedentes-equivalencias/:idNormaSDIN",
    texto_definitivo: "analisis-epistemologico/texto-definitivo/:idNormaSDIN"
}

export const rutasAdmin = {
    home: "/administracion",
    tipos_normas: "tipos-de-normas",
    subtipos_normas: "subtipos-de-normas",
    reparticiones: "reparticiones",
    usuarios: "usuarios",
    jerarquia: "jerarquia",
    cuentas: "cuentas",
    usuarios_bo: "usuarios-bo"
}